### ISSUE TITLE
Do you have discord?

### ISSUE THREAD

**Issue by howardpen9** [NethermindEth/Forta-Agents#149]
Wanna help to build agent too

**Comment by e1Ru1o** [comment]
hello @howardpen9 you can become an agent developer if you want, everyone can. If you are looking for guidance check the Forta site https://www.forta.org/, there you can find all the information, important links and also their Discord.

**Comment by e1Ru1o** [comment]
You can also apply for our internship or full-time position.
Contact us here talent@nethermind.io
