### ISSUE TITLE
Large profit bot anomaly score is too low

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/Forta-Agents#364]
For large profits, I wonder whether the AD score could be made dependent on the amount of profit. So a large amount would lead to a more anomalous score. E.g. https://explorer.forta.network/alert/0x27acb6d08d27983e2d18cdb8dda388764218779e7f863a5908ac367c18e6e296 has a huge profit.

**Comment by Vxatz** [comment]
Fixed on https://github.com/NethermindEth/Forta-Agents/pull/369
