### ISSUE TITLE
FP issue - Native ice phishing

### ISSUE THREAD

**Issue by Ivan1905** [NethermindEth/Forta-Agents#392]
Vasilis,

Here another set of addresses which were flagged by the scam detector as native ice phishers. In such cases, the addresses are receiving native assets and swaping them to unknown coins, which may part of a pump scheme rather than a native ice phishing scam. Also, addresses that are sending the native assets (targets), are sending the native assets across different EOAs which are doing the same (swapping the native assets to unknown coins).

Example 1:
Forta alert: https://explorer.forta.network/alert/0x05dd28cd493647b5adedfb257d12b73e63225c359074726afc7552e90444867b
Etherscan: https://bscscan.com/address/0x14006359917cd005917270d13fc964ebb07ac545

Example 2:
Forta alert: https://explorer.forta.network/alert/0x8f895efbfc2a97b13487a82e903b67c03cac013dd54adc376e22b7ed51202b27
Etherscan: https://bscscan.com/address/0x13bb163b4358a5d82245a8bdb8e1d3eb8984611a

Example 3:
Forta alert: https://explorer.forta.network/alert/0xe04a046bad97e17d7efd390462eb399369bff37fbf31c23c20a86304ade552a9
Etherscan: https://bscscan.com/address/0x62d844973d557902f392aea2ffffcde16266644e

**Comment by Vxatz** [comment]
@Ivan1905, I notice that the "victims" in these examples have in common that just a few blocks (1-2) before sending funds to the "attacker", they were also involved in another transfer, which is highly unlikely for a real victim. I think adding this check would mitigate most of these FPs.

**Comment by christian-forta** [comment]
thumbs up!
