### ISSUE TITLE
FP issue - SOCIAL-ENG-NATIVE-ICE-PHISHING 

### ISSUE THREAD

**Issue by Ivan1905** [NethermindEth/Forta-Agents#394]
There are cases where the hacker only drains one wallet. In addition to that, seems that the target was not fully drained and was only taken a few cents compared to the native asset that the target is holding.

Example 1:
https://explorer.forta.network/alert/0x91e0185703e127cb2a0f0588e0774441087376fd1bf937260f3bd449d8e82329
https://polygonscan.com/address/0x8bbc3cbd54068d7551e9e891d2b341719dc1a8c8

In this case target is drained by 2.79 matic but their holding is more than 40.

Example 2:
https://explorer.forta.network/alert/0x67811e04347afc05ce48b4c679bac48ea003dbb016a214104bee77803cbaeb38
https://polygonscan.com/address/0x2ae6d0bb4b223952df11c4998f88b10cbc9f551b

In this case target is drained by 0.18 matic but their holding is more than 5.

**Comment by Vxatz** [comment]
Hi @Ivan1905, this alert did intentionally not contain any thresholds for the number of victims, should I change it?

Also, I believe that in social engineering attacks, attackers are intentionally not targeting to empty the victim's wallet, but I can also add a balance check.

**Comment by christian-forta** [comment]
i concur soc native ice phishing doesnt necessarily ask for all funds. maybe we could split the alert into two, so we have one that monitors for actual draining and one for partial. This wouldnt quite address the FP issue though. 

Given the function sig points to claim and mint, the To address is an EOA, I dont think these are FPs. ... unless its someone fat fingering it; but in this case, the weighted impact of this FP would be very low. 

I would recommend to close as wont fix.
