### ISSUE TITLE
FP mitigation -SOCIAL-ENG-NATIVE-ICE-PHISHING

### ISSUE THREAD

**Issue by Ivan1905** [NethermindEth/Forta-Agents#397]
Hi vasilis,

Do you know why this alert could have triggered? 

https://explorer.forta.network/alert/0xd6a5d1d948a560480665e48c9f4164599e3f2882e854e870ee53698bf6663536

Sound like Selliix is a legit payment platform, is there a way we could mitigate this one?

**Comment by Vxatz** [comment]
Hi @Ivan1905, thank you for noticing this.
I added a check that there should be only one native token transfer per transaction (which would most probably be the case in a phishing attack withdrawal).
