### ISSUE TITLE
FP mitigation - native ice phishing

### ISSUE THREAD

**Issue by Ivan1905** [NethermindEth/Forta-Agents#398]
Hi vasilis, 

I have watched two different cases where I believe that the scam detector is wrongly assessing addresses as native ice phishers.

https://explorer.forta.network/alert/0xa19559cf3a311db0ad3ed3fe66029d23479b27391b4c0526fc2bd20a4df12bbb
In this case the address flagged is 0xf4067e98c9b842373ab87206eeb91d0cc45be880. What can be seen is that all targets are sending the eth as soon as they are receiving it. 

The second case is something different. https://explorer.forta.network/alert/0xbb8f6082b73be1be9372524611ec04622fda5b7e8c181d7ab41c3f92cfb1fb04
In this one the suspected hacker 0x62e166862Ce448098D85885BC8968B182DF159a3 is stealing 0 native assets (matic) from the targets.

**Comment by Vxatz** [comment]
Hi @Ivan1905,
For the 1st case, based on these transactions,  I increased the number of previous-blocks-to-check for transfers involving the "victim" from 2 to 10.

For the 2nd case, the bot checks that the value should be >0. 
If you notice the victims on the [underlying alert](https://explorer.forta.network/alert/0x6273cf25bad3ef785af40cd7104973f12ae647adcebf95c3fc48ebd45361cccb) are all sending a non-zero amount of MATIC to the "attacker" (e.g. this [transaction](https://polygonscan.com/tx/0x275179a0957321a4e292b4742a8f4adf979693c36e0ece1952ac4ee27606f3f8))
