### ISSUE TITLE
Social engineering ice phishing - FP

### ISSUE THREAD

**Issue by Ivan1905** [NethermindEth/Forta-Agents#408]
Hi Vasilis,

Found an FP here.

Seems this address was labeled as a social engineering ice phisher as it received a self transaction with a message.
Attaching the wallet here: https://etherscan.io/address/0xe9e22d358270509e058c7132bea2e62fa197dcb4

I was wondering if there could exist some sort of restriction so that these alerts don't trigger anymore.

**Comment by Vxatz** [comment]
Hi @Ivan1905, 

the bot does have a mechanism to filter out `to = from` transactions.
The alert associated with the address you've linked is this: https://explorer.forta.network/alert/0xfd4b61d1a44fe93b2bd0f25c4b241e36a0367d2c7e8c2814b20a26def42e2ad5, and I believe it's legit. Could you look into it?
