### ISSUE TITLE
Native ice phishing - FP

### ISSUE THREAD

**Issue by Ivan1905** [NethermindEth/Forta-Agents#410]
Vasilis,

Another sort of FPs that I found. In this particular case, what are considered as targets are bridging to the same chain (chains that in fact do not have a token). This gives me an indicator that in fact targets are rather airdrop hunters.

E.g1: https://etherscan.io/address/0x093981687b72003ef1824e57841266e93bff22eb

E.g2:https://etherscan.io/address/0x4a876ce99c6467e229f81a534993d8a781bb002a

**Comment by Vxatz** [comment]
Hi @Ivan1905, I published a fix for both this and https://github.com/NethermindEth/Forta-Agents/issues/409.
