### ISSUE TITLE
Private key compromise 

### ISSUE THREAD

**Issue by Ivan1905** [NethermindEth/Forta-Agents#413]
Hi vasilis,

I revisited the alerts of the private key compromise bot. I noticed that the bot is flagging many addresses that are receiving native token dust from a bunch of addresses. It is hard to determine if the address is stealing a bunch of addresses or if the receiver is consolidating dust for instance. IMHO it would be weird that the scammer is targeting dozens of addresses and they all have less than $5 worth in native tokens.
I was wondering if you could create a "PKC-3" to mitigate these cases. What I thought is for these cases that at least two assets should be transferred or the combination of all the assets transferred should be worth a minimum X in USD. That is what I came up with but would to hear you as well if you have any idea.

**Comment by 0xtaf** [comment]
hey @Ivan1905 , I'll look into it. thank you

**Comment by 0xtaf** [comment]
fixed in https://github.com/NethermindEth/Forta-Agents/pull/422
