### ISSUE TITLE
FP: large profit bot triggering on remove liquidity invokations

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/Forta-Agents#420]
https://explorer.forta.network/alert/0xe640bf5a5064473e3d681f2e1e3b0ac49f594a439284d49032f95d624bae4b8c

Could we filter out tx that call remove liquidity functions?

**Comment by christian-forta** [comment]
Also this one: its a withdrawl from a wrapped token: https://explorer.forta.network/alert/0x3f90b4afa611b8aae42477fb4191d86c99795d82b3cf4e8d59b026d7129d38fc

**Comment by 0xtaf** [comment]
fixed in https://github.com/NethermindEth/Forta-Agents/pull/421
