### ISSUE TITLE
FN on native ice phishing

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/Forta-Agents#424]
This contract is not source code verified, but I think we would see a withdrawl and claim function. Can we assess it statically without the source code (based on function hashes)?

https://etherscan.io/tx/0x9116385e9a4d95cd4e7c1e7cca35b4bbf458287aa9c2c1696ec1c75b87de1db1

NOte, while NIP-3 triggered, it seems like that one is too noisy.

**Comment by Vxatz** [comment]
Fixed on https://github.com/NethermindEth/Forta-Agents/pull/428.
