### ISSUE TITLE
FP on large profit bot

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/Forta-Agents#436]
https://explorer.forta.network/alert/0xef4db3e3a0aa153fb25cdb4855f1a7313067474c05f0d98b19448c0e7ec5034a

https://explorer.phalcon.xyz/tx/eth/0xfc0a12100d8f4f3caee71524525971f2b7e5df86c53e77c8aca73951fbe375b5

seems like the ETH value isnt taken into account, such that it appears to be a large profit where in fact its a wash.

**Comment by Vxatz** [comment]
I think that what's gone wrong in this is that the USDT price wasn't fetched by Coingecko (ETH price is taken into account and that's the reason bot outputted a "profit")

**Comment by Vxatz** [comment]
Fixed on https://github.com/NethermindEth/Forta-Agents/pull/447.
