### ISSUE TITLE
FP on high gas usage

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/Forta-Agents#440]
https://explorer.phalcon.xyz/tx/bsc/0xc60d91a74366c9fbf66ac723b560b738489290368f181f2d5b8001774b63bda1
https://explorer.forta.network/alert/0x913dae7bd30db98fba15046fae9cc7226178328b87fc1e4e18cb30a599f18147

seems to report on failed tx; lets exclude those or put them on diff alert id.

**Comment by Vxatz** [comment]
Fixed on https://github.com/NethermindEth/Forta-Agents/pull/448.
