### ISSUE TITLE
FN on attack detector due to incorrect AD score on asset drained alert

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/Forta-Agents#450]
https://explorer.forta.network/alert/0x135993f6cb1c9d62d75b4dd60a5f77d95045b1fc4d56bd93d98a73ab91b8c7db

shows AD score of 1.0, which is considered normal. I would expect a lower value for an asset drained alert like that.

**Comment by Vxatz** [comment]
This has been fixed.
